---
- name: DEPLOY AS3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    uri_method: POST

  vars_files:
    - ../creds/big_creds.yaml


  tasks:

  - name: REST CALL TO BIG-IP
    uri:
      url: https://18.168.126.166/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','./as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_output

  - name: DEBUG AS as3_output
    debug:
      msg: "My AS3 output {{ as3_output }}"      
...